export const modules = [
  {
    id: "data-ai",
    short: "DS",
    name: "数据科学与 AI",
    targetHours: 14,
    color: "#2d5bff",
    description: "Python、SQL、统计、机器学习与项目实践",
  },
  {
    id: "cpa",
    short: "CPA",
    name: "CPA",
    targetHours: 10,
    color: "#dd4d3f",
    description: "以年度大纲为轴的章节学习、做题与复习",
  },
  {
    id: "civil",
    short: "公考",
    name: "考公考编",
    targetHours: 8,
    color: "#7d5abb",
    description: "行测专项、申论输出与限时训练",
  },
  {
    id: "english",
    short: "EN",
    name: "英语",
    targetHours: 7,
    color: "#16806a",
    description: "口语、通用英语、专业英语与论文表达",
  },
  {
    id: "career",
    short: "CARE",
    name: "求职维护",
    targetHours: 1,
    color: "#b27b21",
    description: "每周摘要、能力缺口与材料维护",
  },
  {
    id: "review",
    short: "REV",
    name: "复盘",
    targetHours: 2,
    color: "#53636d",
    description: "周计划、问题诊断与 Obsidian 导出",
  },
];

export const starterTasks = [
  {
    title: "完成一个数据科学深度学习块",
    moduleId: "data-ai",
    minutes: 120,
  },
  { title: "CPA 章节学习与基础题", moduleId: "cpa", minutes: 90 },
  { title: "行测专项训练", moduleId: "civil", minutes: 90 },
  { title: "论文英语：摘要精读与复述", moduleId: "english", minutes: 60 },
];

export const yearlyPhases = [
  {
    id: "foundation",
    name: "打底",
    weeks: "第 1–12 周",
    objective: "建立稳定节奏，补齐必要基础。",
    evidence: "每个主模块完成一份基线测评与首个可展示成果。",
  },
  {
    id: "system",
    name: "成体系",
    weeks: "第 13–26 周",
    objective: "从零散学习进入完整知识树。",
    evidence: "形成 CPA 章节框架、数据项目与英语表达素材库。",
  },
  {
    id: "reinforce",
    name: "强化",
    weeks: "第 27–39 周",
    objective: "用错题、限时训练与项目迭代暴露短板。",
    evidence: "完成阶段模考、项目复盘和专业英文输出。",
  },
  {
    id: "sprint",
    name: "冲刺",
    weeks: "第 40–52 周",
    objective: "围绕考试与成果交付收束投入。",
    evidence: "形成可考试、可面试、可复用的最终成果集。",
  },
];

export const learningPaths = {
  "data-ai": [
    { id: "ds-python-sql", title: "Python 与 SQL", focus: "数据处理、查询与可复现分析", output: "完成一份真实数据分析报告" },
    { id: "ds-statistics", title: "统计与实验", focus: "概率、推断、回归与 A/B 测试", output: "解释一组业务实验结果" },
    { id: "ds-analysis", title: "分析与可视化", focus: "指标体系、探索分析与信息表达", output: "制作一份面向决策的数据故事" },
    { id: "ds-ml", title: "机器学习", focus: "建模、验证、特征与误差分析", output: "交付一个带评估报告的模型" },
    { id: "ds-dl", title: "深度学习", focus: "神经网络、Transformer 与训练流程", output: "复现一个小型模型实验" },
    { id: "ds-ai", title: "AI 系统", focus: "LLM、RAG、智能体、评测与工程边界", output: "构建一个可演示的 AI 工具" },
  ],
  cpa: [
    { id: "cpa-framework", title: "会计框架", focus: "准则逻辑、分录与报表勾稽", output: "画出章节框架并完成基础题" },
    { id: "cpa-core", title: "核心科目推进", focus: "按年度教材与大纲逐章学习", output: "形成章节笔记与题型索引" },
    { id: "cpa-errors", title: "错题回炉", focus: "定位概念、条件与计算错误", output: "建立可重复复习的错题卡" },
    { id: "cpa-cases", title: "综合案例", focus: "跨章节判断、计算与书面表达", output: "完成限时综合题与复盘" },
  ],
  civil: [
    { id: "civil-baseline", title: "基线测评", focus: "行测各模块正确率与速度", output: "获得分模块能力基线" },
    { id: "civil-special", title: "行测专项", focus: "资料、判断、言语与数量", output: "形成稳定解题流程" },
    { id: "civil-writing", title: "申论表达", focus: "概括、分析、对策与文章", output: "每周完成一份限时输出" },
    { id: "civil-mock", title: "整卷模考", focus: "时间分配、取舍与复盘", output: "连续记录分数和失分原因" },
  ],
  english: [
    { id: "en-vocabulary", title: "主动词汇", focus: "词族、搭配、例句与间隔回忆", output: "建立能说能写的表达库" },
    { id: "en-listening", title: "听力与语音", focus: "精听、影子跟读、重音与连读", output: "完成逐句听写和跟读录音" },
    { id: "en-speaking", title: "口语输出", focus: "复述、观点陈述与自我纠错", output: "完成 3–5 分钟无稿表达" },
    { id: "en-writing", title: "结构化写作", focus: "段落逻辑、论证与改写", output: "完成一篇短文并建立错误清单" },
    { id: "en-professional", title: "专业英语", focus: "数据、AI 与财务场景表达", output: "完成一次专业概念英文讲解" },
    { id: "en-paper", title: "论文英语", focus: "摘要、方法、结果与局限表达", output: "用英文讲清一篇专业论文" },
  ],
  career: [
    { id: "career-direction", title: "方向维护", focus: "数据、AI 与财务交叉岗位", output: "更新目标岗位画像" },
    { id: "career-evidence", title: "经历证据库", focus: "项目、技能与量化结果", output: "维护可复用的简历素材" },
    { id: "career-market", title: "窗口观察", focus: "9–10 月与 3–4 月招聘节奏", output: "每周保留一次市场摘要" },
    { id: "career-switch", title: "模式切换", focus: "招聘窗口前的材料与练习", output: "在需要时切换为求职主线" },
  ],
  review: [
    { id: "review-facts", title: "收集事实", focus: "时间、成果、错题与身体状态", output: "导出本周客观数据" },
    { id: "review-diagnose", title: "诊断问题", focus: "拖延、难度、精力与任务定义", output: "找到一个主要约束" },
    { id: "review-adjust", title: "调整投入", focus: "增加、减少、保持与暂停", output: "给下周设置三个关键成果" },
    { id: "review-archive", title: "沉淀 Obsidian", focus: "长期规划与决策留痕", output: "完成一篇周复盘" },
  ],
};

export const moduleMilestones = {
  "data-ai": ["Python / SQL 基础", "统计与数据分析", "机器学习", "端到端项目"],
  cpa: ["年度大纲", "章节理解", "错题回炉", "综合案例"],
  civil: ["资料与判断", "言语与数量", "申论", "限时模考"],
  english: ["核心词汇", "听力与跟读", "论文英语", "口头表达"],
  career: ["方向维护", "JD 能力提取", "经历库", "阶段切换"],
  review: ["周数据", "问题诊断", "下周调整", "导出 Obsidian"],
};

export function moduleById(id) {
  return modules.find((item) => item.id === id);
}

export const paperCategories = [
  { id: "all", name: "全部" },
  { id: "data", name: "数据科学" },
  { id: "ai", name: "AI" },
  { id: "finance", name: "财务" },
];

export const dataAiTheory = [
  {
    id: "ds-python-sql",
    index: "01",
    title: "计算与数据基础",
    duration: "6–8 周",
    question: "怎样把原始数据变成可信、可复现的分析对象？",
    theory: ["Python 数据模型与函数", "SQL 查询、连接与窗口函数", "NumPy 向量化与 pandas 表格运算", "Git、环境与可复现工作流"],
    practice: "完成一份包含清洗、查询、可视化与结论的公开数据分析。",
  },
  {
    id: "ds-statistics",
    index: "02",
    title: "统计推断与实验",
    duration: "6–8 周",
    question: "数据中的差异是信号、偏差，还是随机波动？",
    theory: ["概率分布与抽样", "估计、置信区间与假设检验", "线性/逻辑回归", "A/B 测试、因果意识与常见陷阱"],
    practice: "从指标定义到结论，完整解释一次业务实验。",
  },
  {
    id: "ds-analysis",
    index: "03",
    title: "分析与决策表达",
    duration: "4–6 周",
    question: "怎样从业务问题出发，而不是从图表出发？",
    theory: ["指标树与问题拆解", "探索性分析", "时间序列与群组分析", "可视化选择与数据叙事"],
    practice: "制作一份结论先行、能支持决策的数据故事。",
  },
  {
    id: "ds-ml",
    index: "04",
    title: "机器学习",
    duration: "8–10 周",
    question: "怎样判断模型真的能泛化，而不是记住训练数据？",
    theory: ["监督与无监督学习", "数据拆分、交叉验证与泄漏", "特征工程与 Pipeline", "指标、误差分析与可解释性"],
    practice: "交付一个含基线、验证、误差切片与模型卡的预测项目。",
  },
  {
    id: "ds-dl",
    index: "05",
    title: "深度学习",
    duration: "8–10 周",
    question: "表示是如何被学习出来的，训练为何会成功或失败？",
    theory: ["张量、反向传播与优化", "CNN 与序列建模", "Attention 与 Transformer", "正则化、调参与实验管理"],
    practice: "用 PyTorch 复现一个小模型，并记录训练曲线与失败实验。",
  },
  {
    id: "ds-ai",
    index: "06",
    title: "生成式 AI 系统",
    duration: "持续迭代",
    question: "怎样把模型能力变成可靠、可评测的产品系统？",
    theory: ["LLM 推理、提示与结构化输出", "Embedding、检索与 RAG", "工具调用与智能体状态", "评测、安全、成本与可观测性"],
    practice: "构建一个有数据集、有评测、有失败分析的 AI 工具。",
  },
];

export const learningResources = [
  { stageId: "ds-python-sql", title: "The Python Tutorial", provider: "Python 官方文档", type: "文档", url: "https://docs.python.org/3/tutorial/", note: "先掌握控制流、数据结构、函数、模块与异常。" },
  { stageId: "ds-python-sql", title: "Getting started with pandas", provider: "pandas 官方文档", type: "教程", url: "https://pandas.pydata.org/docs/getting_started/", note: "配合一份真实 CSV 边查边做，不要求一次读完。" },
  { stageId: "ds-ml", title: "Machine Learning in Python with scikit-learn", provider: "Inria / scikit-learn", type: "免费课程", url: "https://inria.github.io/scikit-learn-mooc/", note: "覆盖预处理、验证、Pipeline 与模型选择，适合作为机器学习主课。" },
  { stageId: "ds-ml", title: "Machine Learning Crash Course", provider: "Google for Developers", type: "免费课程", url: "https://developers.google.com/machine-learning/crash-course", note: "用短单元补齐损失函数、分类、数据与公平性概念。" },
  { stageId: "ds-dl", title: "Learn the Basics", provider: "PyTorch Tutorials", type: "教程", url: "https://docs.pytorch.org/tutorials/beginner/basics/", note: "从张量到训练循环，完成后自己重写一次。" },
  { stageId: "ds-dl", title: "Practical Deep Learning for Coders", provider: "fast.ai", type: "课程 + 书", url: "https://course.fast.ai/Resources/book.html", note: "以可运行项目理解深度学习，再回填数学细节。" },
  { stageId: "ds-ai", title: "LLM Course", provider: "Hugging Face", type: "免费课程", url: "https://huggingface.co/learn/llm-course/chapter1/1", note: "学习 Transformer、微调、数据处理与模型分享。" },
  { stageId: "ds-ai", title: "AI Agents Course", provider: "Hugging Face", type: "免费课程", url: "https://huggingface.co/learn/agents-course/unit1/introduction", note: "理解工具、动作、观察与智能体工作流。" },
  { stageId: "ds-ai", title: "Full Stack Deep Learning", provider: "FSDL", type: "工程课程", url: "https://fullstackdeeplearning.com/course/2022/", note: "补齐从模型到数据、部署、监控和团队协作的工程视角。" },
  { stageId: "ds-ai", title: "OpenAI Cookbook", provider: "OpenAI", type: "代码案例", url: "https://github.com/openai/openai-cookbook", note: "把案例改写成自己的小实验，并记录边界与成本。" },
];

export const codingExercises = [
  {
    id: "pandas-quality-audit",
    stageId: "ds-python-sql",
    domain: "data",
    title: "pandas 数据质量审计",
    difficulty: "基础",
    minutes: 45,
    brief: "识别缺失、重复和异常值，输出可复用的数据质量报告。",
    goal: "实现 audit_dataframe(df)，返回行列数、缺失率、重复行数和数值列范围。",
    checks: ["不修改输入 DataFrame", "缺失率按降序排列", "能处理没有数值列的数据"],
    starterCode: `import pandas as pd\n\ndef audit_dataframe(df: pd.DataFrame) -> dict:\n    \"\"\"Return a compact, serializable data-quality report.\"\"\"\n    # TODO: implement without mutating df\n    pass\n\nif __name__ == \"__main__\":\n    sample = pd.DataFrame({\"amount\": [10, None, 10], \"city\": [\"A\", \"B\", \"A\"]})\n    print(audit_dataframe(sample))\n`,
  },
  {
    id: "ab-test-interval",
    stageId: "ds-statistics",
    domain: "data",
    title: "A/B 测试置信区间",
    difficulty: "进阶",
    minutes: 60,
    brief: "比较两个转化率，并用区间而不是只用 p 值表达不确定性。",
    goal: "实现比例差的 95% 置信区间，并输出业务可读结论。",
    checks: ["验证样本量与成功数", "返回点估计和上下界", "说明统计显著不等于业务重要"],
    starterCode: `from math import sqrt\n\ndef conversion_lift_interval(success_a, total_a, success_b, total_b):\n    # TODO: return {lift, lower, upper}\n    pass\n\nprint(conversion_lift_interval(120, 2000, 151, 2050))\n`,
  },
  {
    id: "cohort-retention",
    stageId: "ds-analysis",
    domain: "data",
    title: "用户留存 Cohort",
    difficulty: "进阶",
    minutes: 75,
    brief: "从事件表构造注册月 × 活跃月的留存矩阵。",
    goal: "写出清晰的分群、周期索引和归一化步骤。",
    checks: ["同一用户同月去重", "第 0 月留存为 100%", "明确时区与月份边界"],
    starterCode: `import pandas as pd\n\ndef retention_matrix(events: pd.DataFrame) -> pd.DataFrame:\n    \"\"\"events columns: user_id, signup_at, event_at\"\"\"\n    # TODO: build a cohort retention matrix\n    pass\n`,
  },
  {
    id: "sklearn-leakage-safe",
    stageId: "ds-ml",
    domain: "data",
    title: "无泄漏建模 Pipeline",
    difficulty: "进阶",
    minutes: 75,
    brief: "将缺失值、标准化与模型放入同一个交叉验证流程。",
    goal: "完成 ColumnTransformer + Pipeline，并报告交叉验证均值与波动。",
    checks: ["预处理只在训练折拟合", "数值与类别列分别处理", "保留一个简单基线"],
    starterCode: `from sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.model_selection import cross_validate\n\ndef build_pipeline(numeric_cols, categorical_cols):\n    # TODO: return a leakage-safe estimator\n    pass\n`,
  },
  {
    id: "numpy-softmax",
    stageId: "ds-dl",
    domain: "ai",
    title: "稳定版 Softmax",
    difficulty: "基础",
    minutes: 35,
    brief: "不用深度学习框架，实现支持批次输入且数值稳定的 Softmax。",
    goal: "实现 softmax(x, axis=-1)，避免大数指数溢出。",
    checks: ["每行概率和为 1", "输入含 1000 时仍有限", "不改变输入数组"],
    starterCode: `import numpy as np\n\ndef softmax(x: np.ndarray, axis: int = -1) -> np.ndarray:\n    # Hint: which constant can be removed without changing the result?\n    pass\n\nlogits = np.array([[1000.0, 1001.0, 1002.0]])\nprint(softmax(logits))\n`,
  },
  {
    id: "scaled-attention",
    stageId: "ds-dl",
    domain: "ai",
    title: "缩放点积注意力",
    difficulty: "进阶",
    minutes: 60,
    brief: "从矩阵运算理解 Q、K、V、缩放和掩码。",
    goal: "仅用 NumPy 实现 scaled_dot_product_attention。",
    checks: ["最后一维权重和为 1", "支持 causal mask", "解释为何除以 sqrt(d_k)"],
    starterCode: `import numpy as np\n\ndef scaled_dot_product_attention(q, k, v, mask=None):\n    # TODO: scores -> mask -> softmax -> weighted values\n    pass\n`,
  },
  {
    id: "rag-retrieval-eval",
    stageId: "ds-ai",
    domain: "ai",
    title: "RAG 检索评测",
    difficulty: "项目",
    minutes: 90,
    brief: "先评测检索，再讨论生成；计算 Recall@k 并列出失败查询。",
    goal: "实现 evaluate_retrieval，输入预测文档与标准答案，输出 Recall@k 和失败样本。",
    checks: ["k 可配置", "重复文档不重复计数", "保留失败案例用于误差分析"],
    starterCode: `def evaluate_retrieval(predictions, relevant_docs, k=3):\n    \"\"\"Both arguments map query_id to document-id lists/sets.\"\"\"\n    # TODO: compute macro Recall@k and collect failures\n    pass\n`,
  },
  {
    id: "agent-state-machine",
    stageId: "ds-ai",
    domain: "ai",
    title: "可控智能体状态机",
    difficulty: "项目",
    minutes: 90,
    brief: "不用框架黑盒，显式建模计划、工具调用、观察、重试和停止。",
    goal: "实现最多 N 步、工具白名单和完整轨迹记录的 agent_loop。",
    checks: ["有最大步数", "工具输入先校验", "每步可追踪且异常可恢复"],
    starterCode: `from dataclasses import dataclass, field\n\n@dataclass\nclass AgentState:\n    messages: list = field(default_factory=list)\n    trace: list = field(default_factory=list)\n    steps: int = 0\n\ndef agent_loop(state, model, tools, max_steps=6):\n    # TODO: plan, validate tool call, observe, stop\n    pass\n`,
  },
];

export const englishVocabulary = [
  { id: "evidence", word: "evidence", phonetic: "/ˈevɪdəns/", pos: "noun", meaning: "证据；用于支持判断的数据或事实", collocation: "empirical evidence", example: "The evidence suggests that the model fails on rare cases." },
  { id: "robust", word: "robust", phonetic: "/rəʊˈbʌst/", pos: "adjective", meaning: "稳健的；在条件变化时仍可靠", collocation: "robust to noise", example: "The estimator is robust to small amounts of missing data." },
  { id: "infer", word: "infer", phonetic: "/ɪnˈfɜːr/", pos: "verb", meaning: "根据证据推断", collocation: "infer from observations", example: "We cannot infer causality from correlation alone." },
  { id: "estimate", word: "estimate", phonetic: "/ˈestɪmeɪt/", pos: "verb / noun", meaning: "估计；基于样本得到近似值", collocation: "estimate the effect", example: "The study estimates the effect of price on demand." },
  { id: "variance", word: "variance", phonetic: "/ˈveəriəns/", pos: "noun", meaning: "方差；衡量数值离散程度", collocation: "bias–variance trade-off", example: "Regularization can reduce variance at the cost of some bias." },
  { id: "bias", word: "bias", phonetic: "/ˈbaɪəs/", pos: "noun", meaning: "偏差；系统性地偏离真实值", collocation: "selection bias", example: "Selection bias limits how broadly we can apply the result." },
  { id: "benchmark", word: "benchmark", phonetic: "/ˈbentʃmɑːrk/", pos: "noun / verb", meaning: "基准；用于比较性能的统一测试", collocation: "evaluate on a benchmark", example: "The model performs well on the benchmark but poorly in production." },
  { id: "deploy", word: "deploy", phonetic: "/dɪˈplɔɪ/", pos: "verb", meaning: "部署；将模型投入实际环境", collocation: "deploy a model", example: "The team deployed the model behind a monitored API." },
  { id: "retrieve", word: "retrieve", phonetic: "/rɪˈtriːv/", pos: "verb", meaning: "检索；从集合中找回相关内容", collocation: "retrieve relevant documents", example: "The system retrieves relevant documents before generating an answer." },
  { id: "revenue", word: "revenue", phonetic: "/ˈrevənjuː/", pos: "noun", meaning: "营业收入；企业日常经营产生的收入", collocation: "recognize revenue", example: "Revenue is recognized when the performance obligation is satisfied." },
  { id: "liability", word: "liability", phonetic: "/ˌlaɪəˈbɪləti/", pos: "noun", meaning: "负债；企业承担的现时义务", collocation: "current liability", example: "The obligation is reported as a current liability." },
  { id: "impairment", word: "impairment", phonetic: "/ɪmˈpeəmənt/", pos: "noun", meaning: "减值；资产账面价值超过可收回金额", collocation: "impairment loss", example: "The company recognized an impairment loss on the asset." },
  { id: "material", word: "material", phonetic: "/məˈtɪəriəl/", pos: "adjective", meaning: "重大的；足以影响报表使用者判断", collocation: "material misstatement", example: "The auditor assessed the risk of material misstatement." },
  { id: "audit", word: "audit", phonetic: "/ˈɔːdɪt/", pos: "noun / verb", meaning: "审计；对财务信息进行独立检查", collocation: "audit evidence", example: "The audit team collected evidence from multiple sources." },
  { id: "cash-flow", word: "cash flow", phonetic: "/ˈkæʃ fləʊ/", pos: "noun", meaning: "现金流；一定期间内现金流入与流出", collocation: "operating cash flow", example: "Operating cash flow improved despite lower reported profit." },
  { id: "stakeholder", word: "stakeholder", phonetic: "/ˈsteɪkhəʊldə/", pos: "noun", meaning: "利益相关者；受组织决策影响的人或群体", collocation: "key stakeholders", example: "The findings were presented to key stakeholders." },
];

export const englishQuickLessons = [
  {
    id: "lesson-evidence",
    prompt: "The conclusion is not supported by enough empirical ____.",
    options: ["evidence", "revenue", "liability"],
    answer: 0,
    explanation: "empirical evidence 表示通过观察或实验获得的证据。",
  },
  {
    id: "lesson-causality",
    prompt: "Which sentence is academically cautious?",
    options: ["The data proves the policy works.", "The result suggests an association, not necessarily causation.", "The policy always causes growth."],
    answer: 1,
    explanation: "论文表达需要区分相关性与因果性，并避免无依据的绝对判断。",
  },
  {
    id: "lesson-model",
    prompt: "A model that remains reliable when inputs contain noise is ____.",
    options: ["material", "robust", "current"],
    answer: 1,
    explanation: "robust 描述系统对噪声、扰动或条件变化不敏感。",
  },
  {
    id: "lesson-finance",
    prompt: "The company recognized an impairment ____ on the asset.",
    options: ["benchmark", "loss", "retrieval"],
    answer: 1,
    explanation: "impairment loss 是财务英语中的固定搭配：资产减值损失。",
  },
  {
    id: "lesson-method",
    prompt: "Choose the clearest method sentence.",
    options: ["We did some tests on data.", "We evaluated the classifier using five-fold cross-validation.", "The model was good in many ways."],
    answer: 1,
    explanation: "专业写作应说明动作、对象和评估方法，而不是使用含糊形容词。",
  },
];

export const shadowingSentences = [
  { id: "shadow-1", text: "The evidence suggests that the model is robust across different datasets.", focus: "重读 evidence、robust 和 datasets；弱读 that。", translation: "证据表明，该模型在不同数据集上都具有稳健性。" },
  { id: "shadow-2", text: "We cannot infer causality from correlation alone.", focus: "cannot 与 causality 清晰连读；句尾下降。", translation: "我们不能仅从相关性推断因果关系。" },
  { id: "shadow-3", text: "The system retrieves relevant documents before generating an answer.", focus: "retrieves 的尾音 /z/；before 后不必停顿。", translation: "系统在生成答案之前检索相关文档。" },
  { id: "shadow-4", text: "Revenue is recognized when the performance obligation is satisfied.", focus: "recognized 与 obligation 是信息重音。", translation: "当履约义务得到满足时确认收入。" },
  { id: "shadow-5", text: "The auditor assessed the risk of material misstatement.", focus: "material misstatement 作为一个意群朗读。", translation: "审计师评估了重大错报风险。" },
  { id: "shadow-6", text: "Our results should be interpreted with caution because the sample is small.", focus: "with caution 轻停顿；because 引出局限。", translation: "由于样本较小，应谨慎解释我们的结果。" },
];

export const fallbackPapers = [
  {
    id: "1706.03762",
    title: "Attention Is All You Need",
    summary: "Introduces the Transformer architecture, replacing recurrence with attention for sequence modeling.",
    url: "https://arxiv.org/abs/1706.03762",
    source: "基础精选",
    categories: ["ai"],
  },
  {
    id: "1810.04805",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    summary: "Presents bidirectional Transformer pre-training and fine-tuning for language understanding tasks.",
    url: "https://arxiv.org/abs/1810.04805",
    source: "基础精选",
    categories: ["ai"],
  },
  {
    id: "1512.03385",
    title: "Deep Residual Learning for Image Recognition",
    summary: "Introduces residual learning to make very deep neural networks easier to optimize.",
    url: "https://arxiv.org/abs/1512.03385",
    source: "基础精选",
    categories: ["ai"],
  },
  {
    id: "1603.02754",
    title: "XGBoost: A Scalable Tree Boosting System",
    summary: "Describes a scalable tree boosting system widely used for structured data problems.",
    url: "https://arxiv.org/abs/1603.02754",
    source: "基础精选",
    categories: ["data", "ai"],
  },
  {
    id: "2005.14165",
    title: "Language Models are Few-Shot Learners",
    summary: "Studies how scale enables language models to perform tasks from instructions and examples in context.",
    url: "https://arxiv.org/abs/2005.14165",
    source: "基础精选",
    categories: ["ai"],
  },
  {
    id: "1201.0490",
    title: "Scikit-learn: Machine Learning in Python",
    summary: "Describes the design and implementation of a widely used Python library for practical machine learning.",
    url: "https://arxiv.org/abs/1201.0490",
    source: "数据科学精选",
    categories: ["data"],
  },
  {
    id: "1206.4656",
    title: "A Few Useful Things to Know About Machine Learning",
    summary: "Collects practical lessons about generalization, representation, evaluation, and common modeling pitfalls.",
    url: "https://arxiv.org/abs/1206.4656",
    source: "数据科学精选",
    categories: ["data", "ai"],
  },
  {
    id: "1908.10063",
    title: "FinBERT: Financial Sentiment Analysis with Pre-trained Language Models",
    summary: "Adapts pre-trained language models to financial sentiment analysis and evaluates them on finance text datasets.",
    url: "https://arxiv.org/abs/1908.10063",
    source: "财务精选",
    categories: ["finance", "ai"],
  },
  {
    id: "2303.17564",
    title: "BloombergGPT: A Large Language Model for Finance",
    summary: "Presents a large language model trained on financial and general-domain data for finance-focused tasks.",
    url: "https://arxiv.org/abs/2303.17564",
    source: "财务精选",
    categories: ["finance", "ai"],
  },
  {
    id: "2306.06031",
    title: "FinGPT: Open-Source Financial Large Language Models",
    summary: "Explores an open framework for adapting large language models to financial data and applications.",
    url: "https://arxiv.org/abs/2306.06031",
    source: "财务精选",
    categories: ["finance", "ai"],
  },
  {
    id: "1602.06561",
    title: "Deep Learning in Finance",
    summary: "Surveys deep learning methods and their applications to financial modeling and decision problems.",
    url: "https://arxiv.org/abs/1602.06561",
    source: "财务精选",
    categories: ["finance", "data"],
  },
];
